[monitor:///opt/splunk/var/log/splunk_bot/]
disabled = false
index = splunk_bot
sourcetype = splunkbot:audit:finding

[script://./bin/audit_runner.py]
disabled = true
index = splunk_bot
sourcetype = splunkbot:audit:runner
interval = 86400
python.version = python3
