[splunkbot:audit:finding]
KV_MODE = json
TIMESTAMP_FIELDS = audit_time
TIME_FORMAT = %Y-%m-%dT%H:%M:%S%z
SHOULD_LINEMERGE = false
LINE_BREAKER = ([\r\n]+)

[splunkbot:vuln:finding]
KV_MODE = json
TIME_FORMAT = %Y-%m-%dT%H:%M:%S%z
TIME_PREFIX = "scan_time"\s*:\s*"
